version: '3'

volumes:
  bash-history: {}
  bundle-cache: {}
  pg-data: {}

services:
  dev:
    build: .
    volumes:
      - .:/home/phantom/app
      - bash-history:/home/phantom/bash-history
      - bundle-cache:/home/phantom/.bundle
    links:
      - db
    environment:
      - SERVICE_NAME=rails_app.dev

  db:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=phantom
      - POSTGRES_PASSWORD=secret
    volumes:
      - .:/home/phantom/app
      - pg-data:/var/lib/postgresql/data/
